// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

export const awsMobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:8aa0a534-be90-4bba-9cda-8a8b6a102f9d',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_Ld5wvAKdQ',
  aws_user_pools_web_client_id: '60jfaa14paebti2dqtk79d1kda',
  oauth: {},
};
